[package]
name = "inference-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2"
pest_derive = "2"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
image = "0.25"
imageproc = "0.25"
ab_glyph = "0.2"
dioxus = "0.7.9"
base64 = "0.22.1"
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
